spring.application.name=ai-study-assistant
spring.datasource.url=jdbc:postgresql://localhost:5432/ai_study_assistant
spring.datasource.username=postgres
spring.datasource.password=Sushant_13161906

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true